{{- range .Values.apps }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  namespace: {{ .name }}
spec:
  rules:
  - host: {{ .ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ (index .applications 0).name }}
            port:
              number: 80
---
{{- range .applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image.repo }}
        ports:
        - containerPort: {{ .containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .containerPort }}
---
{{- end }}
{{- end }}
