{{- range .Values.apps }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  namespace: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: {{ .ingress.hostName }}
spec:
  rules:
  - host: {{ .ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ (index .applications 0).name }}
            port:
              number: 80
---
{{- range .applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.name }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image.repo }}
        ports:
        - containerPort: {{ .containerPort }}
        resources:
          requests:
            cpu: 1500m
          limits:
            cpu: 1500m
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .containerPort }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}-hpa
  namespace: {{ $.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-service-monitor
  namespace: {{ $.name }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: {{ .name }}
  endpoints:
  - port: 80
    interval: 3s
    path: /actuator/prometheus
{{- end }}
{{- end }}
