{{ range $environment, $values := .Values.appEnvironments }}

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: {{ $environment }}
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
      values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  releaseName: prometheus-adapter
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-adapter
    version: 4.2.0
  targetNamespace: monitoring
  values:
    prometheus:
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
      port: 9090

{{ end }}