apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 45.21.0
  targetNamespace: monitoring
  values:

---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: monitoring
spec:
  releaseName: prometheus-adapter
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-adapter
    version: 4.2.0
  targetNamespace: monitoring
  values:
    prometheus:
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
      port: 9090
