{{ range $environment, $values := .Values.appEnvironments }}

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: {{ $environment }}
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - values.yaml
      values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  project: {{ $environment }}
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
    path: charts/prometheus-adapter
    helm:
      valueFiles:
        - values.yaml
      values: |
        prometheus:
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
          port: 9090
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s


{{ end }}