{{ range $environment, $values := .Values.appEnvironments }}

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: devops
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts'
    path: charts/kube-prometheus-stack
    targetRevision: kube-prometheus-stack-40.5.0
    helm:
      {{- with $values.prometheus.values }}
      values: |- {{- toYaml . | nindent 8 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
spec:
  project: {{ $environment }}
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main
    path: charts/prometheus-adapter
    helm:
      {{- with $values.prometheus.values }}
      values: |- {{- toYaml . | nindent 8 }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s0

{{ end }}