apps:
  app0:
    backgroundColor: yellow
    containerPort: 80
    hostName: argo-poc-app0.bsisandbox.com
    image:
      repo: 704855531002.dkr.ecr.us-east-2.amazonaws.com/nginx:5
    name: app0
    replicas: 5
  app1:
    backgroundColor: red
    containerPort: 80
    hostName: argo-poc-app1.bsisandbox.com
    image:
      repo: 704855531002.dkr.ecr.us-east-2.amazonaws.com/nginx:5
    name: app1
    replicas: 5
  app2:
    backgroundColor: blue
    containerPort: 80
    hostName: argo-poc-app2.bsisandbox.com
    image:
      repo: 704855531002.dkr.ecr.us-east-2.amazonaws.com/nginx:5
    name: app2
    replicas: 5
  app3:
    backgroundColor: pink
    containerPort: 80
    hostName: argo-poc-app3.bsisandbox.com
    image:
      repo: 704855531002.dkr.ecr.us-east-2.amazonaws.com/nginx:5
    name: app3
    replicas: 5