{{- range .Values.apps }}
{{- /* guarantees --- is on a newline */ -}}
{{ printf "\n---" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: {{ $.Values.spec.project }}
  source:
    path: k8s/microservices
    repoURL: {{ $.Values.spec.repoUrl }}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      values: |-
        ingress:
          hostName: {{ .ingress.hostName }}
        applications:
{{ toYaml .applications | nindent 10 }}
        project: {{ $.Values.spec.project }}
        repoUrl: {{ $.Values.spec.repoUrl }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
{{- end }}
